"""Created AreaStageProductConig model

Revision ID: 0ef3d1e0498a
Revises: 480feb8a5fd6
Create Date: 2026-03-02 10:56:01.575672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef3d1e0498a'
down_revision: Union[str, None] = '480feb8a5fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_stage_product_config',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_stage_product_config_id'), 'area_stage_product_config', ['id'], unique=False)
    op.add_column('orders', sa.Column('current_area_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_orders_current_area_id'), 'orders', ['current_area_id'], unique=False)
    op.drop_constraint(op.f('orders_area_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'areas', ['current_area_id'], ['id'])
    op.drop_column('orders', 'area_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_area_id_fkey'), 'orders', 'areas', ['area_id'], ['id'])
    op.drop_index(op.f('ix_orders_current_area_id'), table_name='orders')
    op.drop_column('orders', 'current_area_id')
    op.drop_index(op.f('ix_area_stage_product_config_id'), table_name='area_stage_product_config')
    op.drop_table('area_stage_product_config')
    # ### end Alembic commands ###
