"""Created User model

Revision ID: 1b61bd2e46d6
Revises: f40a092fc43f
Create Date: 2026-01-12 12:02:50.672562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b61bd2e46d6'
down_revision: Union[str, None] = 'f40a092fc43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('first_lastname', sa.String(), nullable=False),
    sa.Column('second_lastname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_operator', sa.Boolean(), nullable=False),
    sa.Column('is_manager', sa.Boolean(), nullable=False),
    sa.Column('is_supervisor', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_first_lastname'), 'users', ['first_lastname'], unique=False)
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_manager'), 'users', ['is_manager'], unique=False)
    op.create_index(op.f('ix_users_is_operator'), 'users', ['is_operator'], unique=False)
    op.create_index(op.f('ix_users_is_supervisor'), 'users', ['is_supervisor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_supervisor'), table_name='users')
    op.drop_index(op.f('ix_users_is_operator'), table_name='users')
    op.drop_index(op.f('ix_users_is_manager'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_index(op.f('ix_users_first_lastname'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
