"""Created Area model

Revision ID: 3767ad1c5ebd
Revises: 4419bc2d77f5
Create Date: 2026-01-17 21:15:22.938440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3767ad1c5ebd'
down_revision: Union[str, None] = '4419bc2d77f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.add_column('users', sa.Column('area_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_users_area'), table_name='users')
    op.create_foreign_key(None, 'users', 'areas', ['area_id'], ['id'])
    op.drop_column('users', 'area')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index(op.f('ix_users_area'), 'users', ['area'], unique=False)
    op.drop_column('users', 'area_id')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
