"""Updated and added fields to Order model

Revision ID: 42566d84574b
Revises: a38a6d75dc8a
Create Date: 2026-04-30 12:20:07.904150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42566d84574b'
down_revision: Union[str, None] = 'a38a6d75dc8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_organization'), table_name='customers')
    op.add_column('orders', sa.Column('due_date', sa.DateTime(), nullable=False))
    op.add_column('orders', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'due_date')
    op.create_index(op.f('ix_customers_organization'), 'customers', ['organization'], unique=False)
    # ### end Alembic commands ###
