"""Updated User model with new field: area

Revision ID: 4419bc2d77f5
Revises: 24564a4446e1
Create Date: 2026-01-14 11:51:10.336949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4419bc2d77f5'
down_revision: Union[str, None] = '24564a4446e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('area', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_area'), 'users', ['area'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_area'), table_name='users')
    op.drop_column('users', 'area')
    # ### end Alembic commands ###
