"""Created OrderReport model

Revision ID: 480feb8a5fd6
Revises: c714d9ed3e73
Create Date: 2026-02-27 11:50:53.900028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480feb8a5fd6'
down_revision: Union[str, None] = 'c714d9ed3e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_report',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('location_url', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_report_id'), 'order_report', ['id'], unique=False)
    op.create_index(op.f('ix_order_report_order_id'), 'order_report', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_report_order_id'), table_name='order_report')
    op.drop_index(op.f('ix_order_report_id'), table_name='order_report')
    op.drop_table('order_report')
    # ### end Alembic commands ###
