"""Added new field for Task model

Revision ID: 501cdd44dde8
Revises: 53cf0989c0c0
Create Date: 2026-03-24 09:46:47.873737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501cdd44dde8'
down_revision: Union[str, None] = '53cf0989c0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reference_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'reference_url')
    # ### end Alembic commands ###
