"""Update Area (Removed Fields, Add Field). Update User (Removed Fields).

Revision ID: 5e0e4c770601
Revises: e4371a50941c
Create Date: 2026-02-14 20:31:23.686785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0e4c770601'
down_revision: Union[str, None] = 'e4371a50941c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('managed', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('areas_manager_id_fkey'), 'areas', type_='foreignkey')
    op.drop_column('areas', 'manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('areas_manager_id_fkey'), 'areas', 'users', ['manager_id'], ['id'])
    op.drop_column('areas', 'managed')
    # ### end Alembic commands ###
