"""Added join for history_tracks in Order model

Revision ID: 6bbcad792efe
Revises: f421c66fd372
Create Date: 2026-04-25 09:50:48.269258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bbcad792efe'
down_revision: Union[str, None] = 'f421c66fd372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
