"""Altered status field in OrderHistoryTrack

Revision ID: a38a6d75dc8a
Revises: 
Create Date: 2026-04-25 17:36:27.349239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38a6d75dc8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('managed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_areas_created_at'), 'areas', ['created_at'], unique=False)
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_index(op.f('ix_areas_updated_at'), 'areas', ['updated_at'], unique=False)
    op.create_table('customers',
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_organization'), 'customers', ['organization'], unique=False)
    op.create_index(op.f('ix_customers_updated_at'), 'customers', ['updated_at'], unique=False)
    op.create_table('products',
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('ALARM', 'MANIFOLD', name='producttypeenum'), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_type'), 'products', ['type'], unique=False)
    op.create_index(op.f('ix_products_updated_at'), 'products', ['updated_at'], unique=False)
    op.create_table('orders',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('ORDER', 'PRODUCTION', 'BOARDING', name='orderstageenum'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', name='orderstatusenum'), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_area_id'), 'orders', ['area_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_stage'), 'orders', ['stage'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_updated_at'), 'orders', ['updated_at'], unique=False)
    op.create_table('tasks',
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('reference_url', sa.String(), nullable=True),
    sa.Column('from_area_id', sa.UUID(), nullable=False),
    sa.Column('to_area_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_acepted', sa.Boolean(), nullable=False),
    sa.Column('evidence_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_from_area_id'), 'tasks', ['from_area_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_is_acepted'), 'tasks', ['is_acepted'], unique=False)
    op.create_index(op.f('ix_tasks_is_completed'), 'tasks', ['is_completed'], unique=False)
    op.create_index(op.f('ix_tasks_to_area_id'), 'tasks', ['to_area_id'], unique=False)
    op.create_index(op.f('ix_tasks_updated_at'), 'tasks', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('first_lastname', sa.String(), nullable=False),
    sa.Column('second_lastname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('DIRECTIVE', 'AREA_MANAGER', name='userroleenum'), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_table('order_history_track',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('ORDER', 'PRODUCTION', 'BOARDING', name='orderstageenum'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', name='orderstatusenum'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_history_track_area_id'), 'order_history_track', ['area_id'], unique=False)
    op.create_index(op.f('ix_order_history_track_created_at'), 'order_history_track', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_history_track_id'), 'order_history_track', ['id'], unique=False)
    op.create_index(op.f('ix_order_history_track_order_id'), 'order_history_track', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_history_track_product_id'), 'order_history_track', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_history_track_stage'), 'order_history_track', ['stage'], unique=False)
    op.create_index(op.f('ix_order_history_track_updated_at'), 'order_history_track', ['updated_at'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_created_at'), 'order_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_updated_at'), 'order_items', ['updated_at'], unique=False)
    op.create_table('order_report',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('location_url', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_report_created_at'), 'order_report', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_report_id'), 'order_report', ['id'], unique=False)
    op.create_index(op.f('ix_order_report_order_id'), 'order_report', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_report_updated_at'), 'order_report', ['updated_at'], unique=False)
    op.create_table('order_stage_evidence',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('ORDER', 'PRODUCTION', 'BOARDING', name='orderstageenum'), nullable=False),
    sa.Column('evidence_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_stage_evidence_created_at'), 'order_stage_evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_stage_evidence_id'), 'order_stage_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_order_stage_evidence_order_id'), 'order_stage_evidence', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_stage_evidence_stage'), 'order_stage_evidence', ['stage'], unique=False)
    op.create_index(op.f('ix_order_stage_evidence_updated_at'), 'order_stage_evidence', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_stage_evidence_updated_at'), table_name='order_stage_evidence')
    op.drop_index(op.f('ix_order_stage_evidence_stage'), table_name='order_stage_evidence')
    op.drop_index(op.f('ix_order_stage_evidence_order_id'), table_name='order_stage_evidence')
    op.drop_index(op.f('ix_order_stage_evidence_id'), table_name='order_stage_evidence')
    op.drop_index(op.f('ix_order_stage_evidence_created_at'), table_name='order_stage_evidence')
    op.drop_table('order_stage_evidence')
    op.drop_index(op.f('ix_order_report_updated_at'), table_name='order_report')
    op.drop_index(op.f('ix_order_report_order_id'), table_name='order_report')
    op.drop_index(op.f('ix_order_report_id'), table_name='order_report')
    op.drop_index(op.f('ix_order_report_created_at'), table_name='order_report')
    op.drop_table('order_report')
    op.drop_index(op.f('ix_order_items_updated_at'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_created_at'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_order_history_track_updated_at'), table_name='order_history_track')
    op.drop_index(op.f('ix_order_history_track_stage'), table_name='order_history_track')
    op.drop_index(op.f('ix_order_history_track_product_id'), table_name='order_history_track')
    op.drop_index(op.f('ix_order_history_track_order_id'), table_name='order_history_track')
    op.drop_index(op.f('ix_order_history_track_id'), table_name='order_history_track')
    op.drop_index(op.f('ix_order_history_track_created_at'), table_name='order_history_track')
    op.drop_index(op.f('ix_order_history_track_area_id'), table_name='order_history_track')
    op.drop_table('order_history_track')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_updated_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_to_area_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_completed'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_acepted'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_from_area_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_orders_updated_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_stage'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_area_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_products_updated_at'), table_name='products')
    op.drop_index(op.f('ix_products_type'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_customers_updated_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_organization'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_areas_updated_at'), table_name='areas')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_created_at'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
