"""Updated Business Models

Revision ID: aa25566bc1b3
Revises: 0ef3d1e0498a
Create Date: 2026-03-07 12:46:05.765918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa25566bc1b3'
down_revision: Union[str, None] = '0ef3d1e0498a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
