"""Added enum of Order Stages for Stage model name field

Revision ID: c714d9ed3e73
Revises: f71ff6f12a13
Create Date: 2026-02-27 11:16:46.741560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c714d9ed3e73'
down_revision: Union[str, None] = 'f71ff6f12a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    orderstageenum = postgresql.ENUM('ORDER', 'ADMINISTRATION', 'ENGINEERING', 'PRODUCTION', 'TESTING', 'PACKAGING', 'DELIVERY', 'RECEIVEMENT', name='orderstageenum')
    orderstageenum.create(op.get_bind())
    op.execute("ALTER TABLE stages ALTER COLUMN name TYPE orderstageenum USING name::text::orderstageenum")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stages', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ORDER', 'ADMINISTRATION', 'ENGINEERING', 'PRODUCTION', 'TESTING', 'PACKAGING', 'DELIVERY', 'RECEIVEMENT', name='orderstageenum'),
               existing_nullable=False)
    op.drop_constraint(op.f('stages_name_key'), 'stages', type_='unique')
    op.create_index(op.f('ix_stages_name'), 'stages', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stages_name'), table_name='stages')
    op.create_unique_constraint(op.f('stages_name_key'), 'stages', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('stages', 'name',
               existing_type=sa.Enum('ORDER', 'ADMINISTRATION', 'ENGINEERING', 'PRODUCTION', 'TESTING', 'PACKAGING', 'DELIVERY', 'RECEIVEMENT', name='orderstageenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
