"""Created OrderHistoryTrack model

Revision ID: e2cb63b8432d
Revises: 52bd5481b8e2
Create Date: 2026-02-23 09:57:15.639745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cb63b8432d'
down_revision: Union[str, None] = '52bd5481b8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_history_track',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_history_track_area_id'), 'order_history_track', ['area_id'], unique=False)
    op.create_index(op.f('ix_order_history_track_id'), 'order_history_track', ['id'], unique=False)
    op.create_index(op.f('ix_order_history_track_order_id'), 'order_history_track', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('area_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'area_id')
    op.drop_index(op.f('ix_order_history_track_order_id'), table_name='order_history_track')
    op.drop_index(op.f('ix_order_history_track_id'), table_name='order_history_track')
    op.drop_index(op.f('ix_order_history_track_area_id'), table_name='order_history_track')
    op.drop_table('order_history_track')
    # ### end Alembic commands ###
