"""Altered model User with new area_name property

Revision ID: e4371a50941c
Revises: 3767ad1c5ebd
Create Date: 2026-02-02 18:17:13.760911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4371a50941c'
down_revision: Union[str, None] = '3767ad1c5ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
