"""Updated User model

Revision ID: edd7c2492b57
Revises: 1b61bd2e46d6
Create Date: 2026-01-12 12:24:33.811630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd7c2492b57'
down_revision: Union[str, None] = '1b61bd2e46d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.drop_index(op.f('ix_users_is_manager'), table_name='users')
    op.drop_index(op.f('ix_users_is_operator'), table_name='users')
    op.drop_index(op.f('ix_users_is_supervisor'), table_name='users')
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_column('users', 'is_operator')
    op.drop_column('users', 'is_supervisor')
    op.drop_column('users', 'is_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_manager', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_supervisor', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_operator', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.create_index(op.f('ix_users_is_supervisor'), 'users', ['is_supervisor'], unique=False)
    op.create_index(op.f('ix_users_is_operator'), 'users', ['is_operator'], unique=False)
    op.create_index(op.f('ix_users_is_manager'), 'users', ['is_manager'], unique=False)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
