"""New field (category) in areas table

Revision ID: f71ff6f12a13
Revises: 29542d160209
Create Date: 2026-02-27 09:54:52.729315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71ff6f12a13'
down_revision: Union[str, None] = '29542d160209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('category', sa.Enum('ADMINISTRATION', 'ENGINEERING', 'PRODUCTION', 'LOGISTICS', name='areacategoryenum'), nullable=False))
    op.create_index(op.f('ix_areas_category'), 'areas', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_areas_category'), table_name='areas')
    op.drop_column('areas', 'category')
    # ### end Alembic commands ###
